steps:
  - id: build-app
    dir: deployment
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker image build --tag gcr.io/${PROJECT_ID}/demo:${COMMIT_SHA} .